# -*- coding: utf-8 -*-
"""NM Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Me4_UNQqbXAotno_XtPaQTbPJlbPa7A
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

"""# New Section"""

# Load your dataset (replace with your own CSV or API)
df = pd.read_csv("C:/CourseWork/NMProject/sports_performance_data_100.csv")

# Drop duplicates and handle missing values
df.drop_duplicates(inplace=True)
df.fillna(df.median(numeric_only=True), inplace=True)

# Convert categorical columns to lowercase and standardize text
df['Position'] = df['Position'].str.upper()

# Correlation Heatmap
plt.figure(figsize=(12,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

# Distribution of goals
sns.histplot(df['Goals'], bins=20, kde=True)
plt.title("Goals Distribution")
plt.show()

from sklearn.preprocessing import StandardScaler

# 1. Create a performance index using available stats
df['PerformanceIndex'] = df['Goals'] * 4 + df['Assists'] * 3 + df['Tackles'] * 2

# 2. Define high/low performance target using 'Rating'
df['MatchImpact'] = (df['Rating'] > 7.0).astype(int)

# 3. Select numeric features only
features = ['PerformanceIndex', 'PassAccuracy', 'Interceptions', 'Saves']

X = df[features]
y = df['MatchImpact']

# 4. Scale numeric features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Try different models
models = {
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"\n{name} Results:")
    print(classification_report(y_test, y_pred))

for name, model in models.items():
    scores = cross_val_score(model, X_scaled, y, cv=5)
    print(f"{name} Cross-validation Accuracy: {np.mean(scores):.2f}")

best_model = RandomForestClassifier()
best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Save as app.py and run using: streamlit run app.py

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

# Load the dataset
df = pd.read_csv("sports_performance_data_100.csv")

# Feature engineering
df['PerformanceIndex'] = df['Goals'] * 4 + df['Assists'] * 3 + df['Tackles'] * 2
df['MatchImpact'] = (df['Rating'] > 7.0).astype(int)

# Features and target
features = ['PerformanceIndex', 'PassAccuracy', 'Interceptions', 'Saves']
X = df[features]
y = df['MatchImpact']

# Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train the model
model = RandomForestClassifier()
model.fit(X_scaled, y)

# Streamlit UI
st.title("Player Performance Predictor")

# User inputs
performance_index = st.slider("Performance Index", float(df['PerformanceIndex'].min()), float(df['PerformanceIndex'].max()))
pass_accuracy = st.slider("Pass Accuracy (%)", 0.0, 100.0, float(df['PassAccuracy'].mean()))
interceptions = st.slider("Interceptions", int(df['Interceptions'].min()), int(df['Interceptions'].max()))
saves = st.slider("Saves", int(df['Saves'].min()), int(df['Saves'].max()))

# Predict
input_data = scaler.transform([[performance_index, pass_accuracy, interceptions, saves]])
prediction = model.predict(input_data)

st.markdown(f"### Predicted Match Impact: {'🔥 High' if prediction[0] == 1 else '❄️ Low'}")

